# Generated by Django 4.1.4 on 2022-12-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primeiro_app", "0002_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=200, verbose_name="Rua/Avenida")),
                ("numero", models.CharField(max_length=5, verbose_name="Número")),
                ("bairro", models.CharField(max_length=200, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=200, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=200, verbose_name="Estado")),
                ("cliente", models.ManyToManyField(to="primeiro_app.cliente")),
            ],
        ),
    ]
